# 📄 NLP Contract Analysis Demo: Structured AI-Powered Legal Document Understanding

---

## 🎯 Overall Purpose of This Notebook

This notebook demonstrates a **complete, end-to-end Natural Language Processing (NLP) workflow** for contract analysis using a large language model.  

In many real business settings, contracts are long, dense, repetitive, and expensive to review manually.  
A modern NLP pipeline can help analysts, accountants, managers, auditors, and legal teams to:

- identify the **parties** involved in an agreement,
- summarize the **main purpose** of the contract,
- extract **key business terms** such as dates, payment terms, and termination conditions,
- identify **major risks** and legal red flags,
- generate a **decision-oriented executive summary**.

This notebook uses the **Qwen model family** through a hard-coded API configuration, following the same practical demonstration style as the OCR notebook.

---

## 🧠 Why This Notebook Is Structured This Way

Rather than jumping directly into one large block of code, the notebook is divided into a sequence of well-defined stages:
1. environment setup,
2. import and configuration,
3. dataset download and loading,
4. contract preview,
5. LLM-based contract analysis,
6. final reporting and structured output display.

---

## 📥 Global Input and Output of the Entire Notebook

### 📥 Notebook Inputs

This notebook takes the following inputs:

1. **A contract dataset**
   - We load contract text from the **CUAD** dataset in a Colab-friendly way.
   - The notebook prepares a small fixed set of sample contracts for demonstration.

2. **A hard-coded Qwen API configuration**
   - API key
   - endpoint URL
   - HTTP request headers

3. **Prompt instructions**
   - These tell the model exactly how to analyze each contract.

---

### 📤 Notebook Outputs

This notebook produces the following outputs:

1. **Clean previews of the original contract text**
2. **Structured AI analysis for each contract**
3. **A document-level summary table**
4. **A full analysis report table**
5. **A classroom-friendly final narrative report**

---

## 🔄 End-to-End Notebook Flow

```text
┌──────────────────────────────┐
│      Contract Dataset        │
│      (CUAD text files)       │
└──────────────┬───────────────┘
               │
               ▼
┌──────────────────────────────┐
│  Fixed Demo Contract Loader  │
│ (Colab-friendly data access) │
└──────────────┬───────────────┘
               │
               ▼
┌──────────────────────────────┐
│    Original Contract Text    │
│        Preview Stage         │
└──────────────┬───────────────┘
               │
               ▼
┌──────────────────────────────┐
│   Qwen NLP Analysis Engine   │
│  (Prompted contract reader)  │
└──────────────┬───────────────┘
               │
               ▼
┌──────────────────────────────┐
│  Structured Analysis Output  │
│  - parties                   │
│  - purpose                   │
│  - obligations               │
│  - key terms                 │
│  - risk assessment           │
│  - executive summary         │
└──────────────┬───────────────┘
               │
               ▼
┌──────────────────────────────┐
│   Final Report and Tables    │
└──────────────────────────────┘
```

---

## 1. Environment Setup

This section prepares the notebook runtime.

### What this section does
This step installs the Python packages needed for:
- dataset loading,
- API requests,
- tabular summaries,
- notebook display.

### Why this step matters
A Colab runtime starts from a relatively clean environment.  
If we do not explicitly install the required libraries, later cells may fail because the dependencies are missing.

### Conceptual mini-flow

```text
Fresh Colab Runtime
        ↓
Install Required Libraries
        ↓
Ready-to-run NLP Environment
```

In [12]:

# Install the libraries required for this notebook.
# Each package supports a different part of the end-to-end workflow.

# Install the Hugging Face datasets package so we can load CUAD in a Colab-friendly way.
!pip -q install datasets

# Install pandas for building final summary tables.
!pip -q install pandas

# Install requests for direct HTTP calls to the Qwen API endpoint.
!pip -q install requests

## 2. Import Libraries and Configure the API

This section performs the core notebook configuration.

### What this section does
This step:
- imports all Python libraries used later in the notebook,
- defines the hard-coded API key and endpoint,
- creates reusable helper functions for printing sections and making API requests.

### Why this step matters
The notebook needs a single, centralized configuration point so the rest of the workflow stays clean and readable.  
Putting all imports, constants, and helper utilities in one place makes the notebook easier to maintain and easier for students to understand.

### Conceptual mini-flow

```text
Installed Libraries
        ↓
Import Modules
        ↓
Define API Configuration
        ↓
Build Reusable Utilities
        ↓
Notebook Ready for Analysis
```

In [13]:

# Import the requests library so the notebook can send HTTP requests to the Qwen API.
import requests

# Import json so we can safely work with structured API responses.
import json

# Import os so we can inspect paths and environment-related information when needed.
import os

# Import re for regular-expression-based text cleaning and parsing.
import re

# Import time so we can add small pauses between API calls if needed.
import time

# Import pandas so we can build structured summary tables at the end of the notebook.
import pandas as pd

# Import datetime so timestamps can be added to outputs if desired.
from datetime import datetime

# Import display from IPython so DataFrames can be rendered neatly inside the notebook.
from IPython.display import display

# Import load_dataset from the datasets library so CUAD can be downloaded directly in Colab.
from datasets import load_dataset

# Define the hard-coded API key exactly as used in the original notebook style.
API_KEY = "sk-cJvvaaDosK2UQKWvPeyK7HyrRK004ul6L9IN7YdZm00cd7xT"

# Define the complete DashScope-compatible chat completions endpoint.
BASE_URL = "https://api.bianxie.ai/v1/chat/completions"

# Define the default model used for contract analysis.
DEFAULT_MODEL_NAME = "qwen-plus"

# Define a helper function that prints a visible section header for cleaner notebook output.
def print_section(title):
    # Print a long separator line.
    print("\n" + "=" * 100)
    # Print the section title itself.
    print(title)
    # Print another separator line.
    print("=" * 100)

# Define a helper function that creates the HTTP headers required by the API.
def setup_qwen_client():
    # Build the authorization and content-type headers in dictionary form.
    headers = {
        "Authorization": f"Bearer {API_KEY}",
        "Content-Type": "application/json"
    }
    # Return the completed header dictionary.
    return headers

# Create the reusable headers object once so later API calls remain clean.
HEADERS = setup_qwen_client()

# Print a short configuration summary so the user can confirm that setup succeeded.
print_section("STEP 1 — API CONFIGURATION")
print(f"✅ API client configured")
print(f"🔑 API key prefix: {API_KEY[:10]}...{API_KEY[-4:]}")
print(f"🌐 API endpoint: {BASE_URL}")
print(f"🧠 Default model: {DEFAULT_MODEL_NAME}")

====================================================================================================
STEP 1 — API CONFIGURATION
====================================================================================================
✅ API client configured
🔑 API key prefix: sk-cJvvaaD...d7xT
🌐 API endpoint: https://api.bianxie.ai/v1/chat/completions
🧠 Default model: qwen-plus

## 3. Test the API Connection and Load the Contract Dataset

This section combines two closely related setup tasks:
1. verify that the LLM connection works,
2. load a reproducible set of demo contracts.

### What this section does
This step:
- sends a short test request to the API,
- downloads the CUAD dataset in a Colab-friendly format,
- selects a small fixed set of contract examples for the notebook.

### Why this step matters
Before running expensive or time-consuming analysis, we should confirm two things:
- the model can actually be reached,
- the notebook has valid contract text to analyze.

This prevents downstream errors and makes the workflow more robust.

### Conceptual mini-flow

```text
API Configuration + Colab Runtime
              ↓
      Test API Connection
              ↓
      Load CUAD Dataset
              ↓
 Select Fixed Demo Contracts
              ↓
Ready for Contract Preview
```

In [14]:

# Define a helper function that sends a very small test request to the API.
def test_api_connection():
    # Print a visible step header.
    print_section("STEP 2 — API CONNECTION TEST")

    # Build a minimal payload for a lightweight connection test.
    test_payload = {
        "model": DEFAULT_MODEL_NAME,
        "messages": [
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": "Reply with exactly: API connection successful."}
        ],
        "max_tokens": 20,
        "temperature": 0.0
    }

    # Try to call the API and validate the response.
    try:
        # Send the POST request to the configured endpoint.
        response = requests.post(BASE_URL, headers=HEADERS, json=test_payload, timeout=60)

        # Raise an exception immediately if the HTTP status is not successful.
        response.raise_for_status()

        # Convert the response body from JSON text into a Python dictionary.
        response_json = response.json()

        # Extract the assistant content from the standard chat-completions response structure.
        assistant_text = response_json["choices"][0]["message"]["content"]

        # Print a success message and the model reply.
        print("✅ API test succeeded")
        print(f"🤖 Test response: {assistant_text}")

        # Return True so later cells know the API is working.
        return True

    # Catch any exception and report it clearly.
    except Exception as e:
        # Print a failure message.
        print(f"❌ API test failed: {e}")

        # Return False so later cells can avoid analysis requests.
        return False

# Run the API connectivity test and store the result for downstream logic.
api_working = test_api_connection()

====================================================================================================
STEP 2 — API CONNECTION TEST
====================================================================================================
✅ API test succeeded
🤖 Test response: API connection successful.

In [15]:
# Define a helper function that loads CUAD contracts from GitHub instead of local folder.
def load_cuad_demo_contracts():
    # Print a visible step header to make notebook output structured and readable.
    print_section("STEP 3 — LOAD CONTRACTS FROM GITHUB")

    # Define the GitHub repository API URL to list files in the repo.
    api_url = "https://api.github.com/repos/MaggieChen7/CUAD/contents"

    # Send a GET request to GitHub API to retrieve file metadata.
    response = requests.get(api_url)

    # Convert the JSON response into Python data structure (list of files).
    files = response.json()

    # Filter only .txt files (contracts).
    txt_files = [f for f in files if f["name"].endswith(".txt")]

    # Sort file list to ensure deterministic selection (important for teaching reproducibility).
    txt_files = sorted(txt_files, key=lambda x: x["name"])

    # Check if there are enough files available.
    if len(txt_files) == 0:
        raise ValueError("❌ No .txt contract files found in the GitHub repo.")

    # Define how many contracts we want to load for the demo.
    num_samples = 3  # Keep it small for readability and performance.

    # Select the first 3 files (deterministic instead of random).
    selected_files = txt_files[:num_samples]

    # Create an empty list to store structured contract data.
    selected_contracts = []

    # Loop through selected contract files one by one.
    for index, file_info in enumerate(selected_files, start=1):

        # Extract filename from GitHub metadata.
        filename = file_info["name"]

        # Get the raw download URL for the file.
        download_url = file_info["download_url"]

        # Send request to download the file content.
        file_response = requests.get(download_url)

        # Decode file content into text format.
        contract_text = file_response.text

        # Skip files that are too short or empty.
        if not contract_text or len(contract_text.strip()) < 1500:
            continue

        # Create a readable display title (remove ".txt" suffix).
        display_title = filename.replace(".txt", "")

        # Append structured contract information to the list.
        selected_contracts.append({
            "sample_id": f"contract_{index}",  # Unique ID for each contract.
            "filename": filename,  # Original file name.
            "display_title": display_title,  # Clean title for display.
            "content": contract_text,  # Full contract text.
            "word_count": len(contract_text.split())  # Word count for analysis.
        })

    # Check if we successfully loaded any valid contracts.
    if not selected_contracts:
        raise ValueError("❌ No suitable contracts found after filtering.")

    # Print a summary of loaded contracts.
    print(f"✅ Loaded {len(selected_contracts)} fixed demo contracts")

    # Loop through loaded contracts and print basic info.
    for contract in selected_contracts:
        print(f"📄 {contract['display_title']} | {contract['word_count']} words")

    # Return the structured contract list.
    return selected_contracts


# Call the function and store results in the global variable `contracts`.
contracts = load_cuad_demo_contracts()

====================================================================================================
STEP 3 — LOAD CONTRACTS FROM GITHUB
====================================================================================================
✅ Loaded 3 fixed demo contracts
📄 2ThemartComInc_19990826_10-12G_EX-10.10_6700288_EX-10.10_Co-Branding Agreement_ Agency Agreement | 4467 words
📄 ABILITYINC_06_15_2020-EX-4.25-SERVICES AGREEMENT | 4115 words
📄 ACCELERATEDTECHNOLOGIESHOLDINGCORP_04_24_2003-EX-10.13-JOINT VENTURE AGREEMENT | 1911 words

## 4. Preview the Original Contract Text

This section presents the raw source documents before analysis.

### What this section does
This step prints a readable preview of each selected contract.

### Why this step matters
We should see the original legal text before seeing the model output.  
That makes the notebook much more interpretable: users can compare what the model says with what the source document actually contains.

### Conceptual mini-flow

```text
Selected Contract Records
          ↓
Read Original Text
          ↓
Display Structured Preview
          ↓
Human Understanding Before AI Analysis
```

In [16]:

# Print a visible section title for the preview stage.
print_section("STEP 4 — DISPLAY ORIGINAL CONTRACT TEXT")

# Loop through the selected contracts one by one.
for index, contract in enumerate(contracts, start=1):
    # Print a contract-level separator.
    print("\n" + "-" * 100)

    # Print the contract number and display title.
    print(f"📄 CONTRACT {index}: {contract['display_title']}")

    # Print the file-style name used in the notebook record.
    print(f"📁 File name: {contract['filename']}")

    # Print the approximate word count.
    print(f"🧮 Word count: {contract['word_count']}")

    # Print a preview label.
    print("\n📝 ORIGINAL TEXT PREVIEW")
    print("-" * 60)

    # Create a truncated preview so notebook output stays readable.
    preview_text = contract["content"][:6000]

    # Add a continuation marker when the contract is longer than the preview window.
    if len(contract["content"]) > 6000:
        preview_text += "\n\n... [TEXT TRUNCATED FOR PREVIEW]"

    # Print the preview text itself.
    print(preview_text)

====================================================================================================
STEP 4 — DISPLAY ORIGINAL CONTRACT TEXT
====================================================================================================

----------------------------------------------------------------------------------------------------
📄 CONTRACT 1: 2ThemartComInc_19990826_10-12G_EX-10.10_6700288_EX-10.10_Co-Branding Agreement_ Agency Agreement
📁 File name: 2ThemartComInc_19990826_10-12G_EX-10.10_6700288_EX-10.10_Co-Branding Agreement_ Agency Agreement.txt
🧮 Word count: 4467

📝 ORIGINAL TEXT PREVIEW
------------------------------------------------------------
CO-BRANDING AND ADVERTISING AGREEMENT

THIS CO-BRANDING AND ADVERTISING AGREEMENT (the "Agreement") is made as of June 21, 1999 (the "Effective Date") by and between I-ESCROW, INC., with its principal place of business at 1730 S. Amphlett Blvd., Suite 233, San Mateo, California 94402 ("i-Escrow"), and 2THEMART.COM, INC. having its principal place of business at 18301 Von Karman Avenue, 7th Floor, Irvine, California 92612 ("2TheMart").

1. DEFINITIONS.

(a) "CONTENT" means all content or information, in any medium, provided by a party to the other party for use in conjunction with the performance of its obligations hereunder, including without limitation any text, music, sound, photographs, video, graphics, data or software. Content provided by 2TheMart is referred to herein as "2TheMart Content" and Content provided by i-Escrow is referred to herein as "i-Escrow Content."

(b) "CO-BRANDED SITE" means the web-site accessible through Domain Name, for the Services implemented by i-Escrow. The homepage of this web-site will visibly display both 2TheMart Marks and i-Escrow Marks.

(c) "CUSTOMERS" means all users who access Co-Branded Site.

(d) "DOMAIN NAME" means www.iescrow.com/2TheMart.

(e) "ESCROW SERVICES" means services for auction sellers and high bidders whereby an agent holds a buyer's money in trust until the buyer approves the applicable item that was physically delivered, at which time the agent releases the buyer's money to seller, after subtracting the escrow fees.

(f) "INFORMATION TRANSFER MECHANISM" means the mechanism by which 2TheMart transfers to i-Escrow information to populate the applicable i-Escrow transaction and user registration forms.

(g) "LAUNCH DATE" means the first date on which the Co-Branded Site is pointed to in all references to i-Escrow from 2TheMart auction site, and the Information Transfer Mechanism is publicly deployed (post-beta).

(h) "MARKS" means all domain names, trademarks and logos designated by a party for the other party's use in conjunction with such other party's performance under this Agreement.  Marks designated by 2TheMart for i-Escrow's use are referred to herein as "2TheMart Marks" and Marks designated by i-Escrow for 2TheMart' use are referred to herein as "i-Escrow Marks."

(i) "SERVICES" means i-Escrow's implementation and performance of the Escrow Services as of the Effective Date, as modified over time.

(j) "SHADOW SITE" means the site where Co-Branded Site is made available for 2TheMart's testing of the Information Transfer Mechanism prior to being made publicly available.

(k) "TRANSACTION" means a transaction utilizing the Services that actually closes and that was initiated by a Transaction Inquiry from a Customer.

(l) "TRANSACTION INQUIRY" means a Customer's submission of i-Escrow's standard New Transaction Inquiry form (or its successor) on or through the Co-Branded Pages.  Currently this means entry of a description and price of merchandise by a user (buyer or seller) who agrees to abide by the terms and conditions of the Services, together with email address of the other party, regardless of whether or not any Transaction is completed.

Source: 2THEMART COM INC, 10-12G, 8/26/1999





2. DEVELOPMENT AND IMPLEMENTATION.

2.1 OVERVIEW.  As set forth herein, 2TheMart will promote Services to its auction users (buyers and sellers), and i-Escrow shall develop Co-Branded Site, and develop the Information Transfer Mechanism working with 2TheMart to make Services available seamlessly to Customers. Unless otherwise specified, each party shall be responsible for all development, hosting and other costs associated with the pages resident on their servers and all emails to users they send.

2.2 INITIAL INFORMATION TRANSFER MECHANISM DEVELOPMENT. The parties shall negotiate in good faith to determine the initial operation of the Information Transfer Mechanism and to describe such operation and development fees, in a statement of work ("SOW").  Each party shall make available sufficient and qualified engineers to negotiate the SOW.  No SOW shall be binding on the parties unless mutually approved by both parties.  In the event that the parties are unable to agree to an SOW within 2 months following the Effective Date, either party may, in its sole discretion, terminate this Agreement by providing written notice.

Once approved, the parties shall use commercially reasonable efforts to diligently implement their respective obligations under the SOW.  Upon completion of its duties under the SOW, a party shall notify the other party and provide the other party with the opportunity to test and evaluate its work. i-Escrow shall make available the Shadow Site for such testing in a timely manner. Each party shall reasonably cooperate with the other party in effectuating their respective duties under the SOW.  The Information Transfer Mechanism shall not go live until its operation has been approved ("Approval Date") by both parties, such approval not to be unreasonably withheld.

2.3 LAUNCH TIMING.  Each party shall use good faith and reasonable efforts to expeditiously develop the Co-Branded Pages and the Information Transfer Mechanism.  In the event that, after using such efforts, the Launch Date has not occurred within 4 months following the Effective Date, either party may terminate this Agreement by providing written notice.  If

only one party has used good faith and reasonable development efforts, only that party may exercise the foregoing right to terminate.

2.4 RESTRICTIONS ON COMMUNICATIONS.  i-Escrow may place banner advertising on the Co-Branded Site upon prior written approval of 2TheMart, which shall be at the discretion of 2TheMart.  All advertising revenue arising from the banner ads shall be solely i-Escrow's.  i-Escrow shall not run banner advertisements on the Co-Branded Site for any of 2TheMart's competitors. 2TheMart shall provide in writing, a list of companies they would like to exclude, including every time they wish t

... [TEXT TRUNCATED FOR PREVIEW]

----------------------------------------------------------------------------------------------------
📄 CONTRACT 2: ABILITYINC_06_15_2020-EX-4.25-SERVICES AGREEMENT
📁 File name: ABILITYINC_06_15_2020-EX-4.25-SERVICES AGREEMENT.txt
🧮 Word count: 4115

📝 ORIGINAL TEXT PREVIEW
------------------------------------------------------------
EXHIBIT 4.25 INFORMATION IN THIS EXHIBIT IDENTIFIED BY [ * * * ] IS CONFIDENTIAL AND HAS BEEN EXCLUDED BECAUSE IT IS BOTH (I) NOT MATERIAL AND (II) WOULD LIKELY CAUSE COMPETITIVE HARM TO THE REGISTRANT IF PUBLICLY DISCLOSED. SERVICES AGREEMENT This Services Agreement (this "Agreement") is entered into on October 1, 2019 and is made effective as of November 1, 2019 (the "Effective Date"), by and between [ * * * ] (the "Provider"), and TELCOSTAR PTE, LTD., a company organized and existing under the laws of Singapore and Ability Computer & Software Industries Ltd, a company organized and existing under the laws of the State of Israel (each and both of them "Recipient"). Each of the foregoing parties is referred to herein as a "Party" and together as the "Parties". RECITALS A. Recipient wishes to engage the Provider to provide certain services and resources (the "Services") and Provider desires to provide Recipient with the Services all in accordance with the terms and conditions set forth herein. AGREEMENT The Parties hereby agree as follows: 1. Services. 1.1 Provision of Services. (a) Provider agrees to provide the Services set forth on the Exhibit A attached hereto (as such Exhibit may be amended or supplemented pursuant to the terms of this Agreement, the "Exhibit") to Recipient for the respective periods and on the other terms and conditions set forth in this Agreement and in the Exhibit. Notwithstanding the contents of the Exhibit, Provider agrees to respond in good faith to any reasonable request by Recipient for access to any additional services and resources that are necessary for the operation of the Recipient and which are not currently contemplated in the Exhibit, at a price to be agreed upon after good faith negotiations between the Parties. Any such additional services and resources so provided by Provider shall constitute Services under this Agreement and be subject in all respect to the provisions of this Agreement as if fully set forth on the Exhibit as of the date hereof. (b) Recipient may freely assign its rights under this Agreement to receive the Services to any of its affiliates. 1.2 Standard of Service. (a) Provider represents, warrants and agrees that the Services shall be provided in good faith, in accordance with applicable law and in a manner generally consistent with the historical provision of the Services and with the same standard of care as historically provided. (b) Provider shall maintain complete and accurate records relating to the provision of the Services under this Agreement, in such form as Recipient shall approve.





(c) Provider shall use its best efforts to provide for employees or contractors to perform the Services, each of whose names, positions, and respective levels of experience and relevant licenses shall be set out in Exhibit A attached hereto (collectively, the "Provider Representatives"). Provider may not make any change in the Provider Representatives without the prior consent of the Recipient. Provider Representatives shall be dedicated to solely providing the Services to Recipient and shall not provide any such services or resources to Provider or any other customer of Provider. (d) Recipient acknowledges that this Agreement does not create a fiduciary relationship, partnership, joint venture or relationships of trust or agency between the Parties and that all Services are provided by Provider as an independent contractor. (e) Notwithstanding anything to the contrary in this Section 1.2: (a) in the event that Provider uses any subcontractors to perform any Services, Provider is not released from responsibility for its obligations under this Agreement; (b) Provider shall remain fully responsible, financially and otherwise, for the Services provided by each subcontractor to the same extent as if Provider had performed the Services itself (subject to the limitations set forth in this Agreement) and agrees to pay the fees and expenses of any such subcontractor; (c) Provider shall remain ultimately responsible for ensuring that the Services are provided and any such subcontractor performs any such obligations in accordance with the terms of this Agreement, and (d) the obligations with respect to the nature, quality and standards of care set forth in Section 1.2 are satisfied with respect to any Service provided by any subcontractor. (f) Provider shall at all times during the term of this Agreement maintain, or cause to be maintained, the computer software and computer hardware that is used in connection with the Services with substantially the same degree of care, skill and diligence with which Provider maintains, or causes to be maintained, as of the Effective Date, such computer software and computer hardware for itself, consistent with past practices, as of the Effective Date, including without limitation, with respect to type, quality and timeliness of such maintenance. 1.3 Additional Services. Nothing in this Agreement shall be construed to prevent the Recipient from itself performing or from acquiring services from other providers that are similar to or identical to the Services. 1.4 Intellectual Property. (a) Recipient shall own, and Provider hereby irrevocably assigns to the Recipient, all rights, title, and interest in any invention, technique, process, device, discovery, improvement, or know-how, whether patentable or not and all other proprietary rights, industrial rights and any other similar rights, in each case on a worldwide basis, and all copies and tangible embodiments thereof, or any part thereof, in whatever form or medium hereafter made or conceived solely or jointly by Provider while working for or on behalf of the Recipient, which relate to, is suggested by, or results from the Services. (b) At Recipient's request, Provider shall disclose any such invention, technique, process, device, discovery, improvement, or know-how promptly to Recipient. Provider shall, upon request of Recipient, promptly execute a specific assi

... [TEXT TRUNCATED FOR PREVIEW]

----------------------------------------------------------------------------------------------------
📄 CONTRACT 3: ACCELERATEDTECHNOLOGIESHOLDINGCORP_04_24_2003-EX-10.13-JOINT VENTURE AGREEMENT
📁 File name: ACCELERATEDTECHNOLOGIESHOLDINGCORP_04_24_2003-EX-10.13-JOINT VENTURE AGREEMENT.txt
🧮 Word count: 1911

📝 ORIGINAL TEXT PREVIEW
------------------------------------------------------------
EXHIBIT 10.13

                             JOINT VENTURE AGREEMENT

Collectible Concepts Group, Inc. ("CCGI") and Pivotal Self Service Tech, Inc. ("PVSS"), (the "Parties" or "Joint Venturers" if referred to collectively, or the "Party" or Joint Venturer" if referred to singularly), by this Agreement associate themselves as business associates, and not as partners, in the formation of a joint venture (the "Joint Venture"), for the purpose of engaging generally in the business provided for by terms and provisions of this Agreement.

1.   Name of the Joint Venture. The name of the Joint Venture will be MightyCell      Batteries, and may sometimes be referred to as "MightyCell" or the "Joint      Venture" in this Agreement. The principal office and place of business      shall be located in 1600 Lower State Road, Doylestown, PA 18901.

2.   Scope of the Joint Venture Business. The Joint Venture is formed for the      purpose of engaging generally in the business of marketing batteries and      related products, (the "Products") that include the display of licensed      logos, images, brand names and other labels that differentiate them from      the branding (the "PVSS Products") under which PVSS and/or its affiliates,      sell to retailers and distributors in the normal course of their business.      Without in any way limiting the generality of the foregoing, the business      of the Joint Venture shall include:

          (a)  The purchase of Products for resale;           (b)  The acquisition of a license(s) permitting the use of selected                images in the Products;           (c)  The sale and distribution of the Products to retailers and                distributors; and,           (d)  The transaction of such other and further business as is                necessary, advisable, or incidental to the business of the Joint                Venture.           (e)  Develop a global marketing program for licensed Products

     Exhibit A attached hereto, describes by way of example but not limitation      the responsibilities of the Joint Venturers

3.   Capital Contributions. Except as agreed upon by mutual consent, the Joint      Venturers shall not be required to make any capital contribution to the      Joint Venture.

4.   Offices of the Joint Venture. The principal place of business of the Joint      Venture shall be at 1600 Lower State Road, in the City of Doylestown, Bucks      County, Pennsylvania, but may maintain such other offices as the Joint      Venturers may deem advisable at any other place or places within or without      the Commonwealth of Pennsylvania.

5.   Powers and Authority of the Joint Venturers. The Joint Venturers shall have      full and complete charge of all affairs of the Joint Venture. The Joint      Venturers recognize that both of the Joint Venturers are and will continue      to be engaged in the conduct of their respective businesses for their own      account. Neither Joint Venturer shall be entitled to compensation for      services rendered to the Joint Venture as such, but each Joint Venturer      shall be reimbursed for all direct expenses, including travel, office, and      all other out-of-pocket expenses incurred in the operation of the affairs      of the Joint Venture and the promotion of its businesses.

     It is agreed that either Joint Venturer shall, except as provided for      below, have authority to execute instruments of any character relating to      the affairs of the Joint Venture; provided, that without the written      consent or approval of both of the Joint Venturers: (i) the Joint Venture      shall incur no liability of any sort, nor any indebtedness for borrowed      funds; (ii) no assets owned in the name of the Joint Venture be disposed      of; and (iii) no commitment to purchase any item for the Joint Venture      shall be made.

                                       39

6.   Division of Income and Losses. All income and credits, and all losses and      deductions shall be owned and shared among the Joint Venturers as follows:

     50% to Collectible Concepts Group, Inc.

     50% to Pivotal Self Service Tech, Inc.

     Depreciation and all other charges and expenses, which are not expressly      apportioned by this Agreement, shall be apportioned in accordance with      generally accepted accounting principles, consistently applied.

7.   Accounting Provisions. The Joint Venturers shall maintain adequate books      and records to be kept of all the Joint Venture activities and affairs      conducted pursuant to the terms of this Agreement. All direct costs and      expenses, which shall include any insurance costs in connection with the      distribution of the Products or operations of the Joint Venture, or if the      business of the Joint Venture requires additional office facilities than      those now presently maintained by each Joint Venturer, such item shall be





     paid by the Joint Venture. The fiscal year of the Joint Venture shall be      the calendar year, and shall use the cash basis of accounting. If requested      by a Joint Venturer, the Joint Venture books and records shall be audited      as of the close of each year by an independent accountant acceptable to      both Joint Venturers. All books and records of every kind and character, of      the Joint Venture, and other information, shall be kept at the principal      office of the Joint Venture, or at such other place or places as may be      agreed upon by the Joint Venturers, and shall be fully available to each      Joint Venturer or his duly authorized representative, all at reasonable      times. The books of the Joint Venture shall represent the complete record      and report of business operations, including a balance sheet and income and      expense statements reflecting all receipts and disbursements of the Joint      Venture, and such reports shall be submitted to the Joint Venturers on a      regular basis.

8.   Term

... [TEXT TRUNCATED FOR PREVIEW]

## 5. Define the NLP Analysis Pipeline and Run Contract Analysis

This section contains the analytical core of the notebook.

### What this section does
This step:
- defines the prompt used for contract review,
- sends each contract to the Qwen model,
- stores the structured analysis results.

### Why this step matters
This is the stage where raw contract text is transformed into usable business intelligence.  
The prompt is intentionally structured so the model returns:
- parties,
- purpose,
- obligations,
- key terms,
- risk assessment,
- an executive summary.

### Conceptual mini-flow

```text
Original Contract Text
          ↓
Structured Analysis Prompt
          ↓
Qwen Contract Reading
          ↓
Structured Contract Analysis
```

In [17]:

# Define a helper function that builds the analysis prompt for one contract.
def build_contract_analysis_prompt(contract_text):
    # Return a structured prompt that asks the model to analyze the contract clearly and consistently.
    return f"""
You are an expert contract analyst supporting accounting, audit, legal, and business review workflows.

Please analyze the following contract and produce a structured report using the exact section headings below.

CONTRACT TO ANALYZE:
--------------------
{contract_text}

REQUIRED OUTPUT FORMAT:

PARTIES:
- Party A:
- Party B:

MAIN PURPOSE:
- Briefly explain what this contract is about in 2-4 sentences.

MAIN RIGHTS AND OBLIGATIONS:
- Party A obligations:
- Party B obligations:

KEY TERMS:
- Payment or value terms:
- Duration or important dates:
- Termination conditions:
- Liability or indemnity observations:
- Governing law or jurisdiction, if available:

RISK LEVEL:
- Overall risk level: Low / Medium / High
- Main risk factors:

EXECUTIVE SUMMARY:
- Write a concise executive summary in 4-6 bullet points for a business audience.
""".strip()

# Define a helper function that calls the Qwen API for one contract.
def analyze_contract(contract_text):
    # Build the full prompt for the current contract.
    prompt = build_contract_analysis_prompt(contract_text)

    # Create the chat-completions payload sent to the API.
    payload = {
        "model": DEFAULT_MODEL_NAME,
        "messages": [
            {
                "role": "system",
                "content": "You are a precise, business-oriented legal contract analysis assistant."
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        "max_tokens": 1500,
        "temperature": 0.1
    }

    # Send the request to the API inside a try/except block for safer error handling.
    try:
        # Submit the POST request.
        response = requests.post(BASE_URL, headers=HEADERS, json=payload, timeout=120)

        # Raise an exception if the response status is not successful.
        response.raise_for_status()

        # Parse the JSON response body.
        response_json = response.json()

        # Extract the assistant's analysis text.
        analysis_text = response_json["choices"][0]["message"]["content"]

        # Return the model output.
        return analysis_text

    # Catch any exception and return a readable error marker instead of crashing the entire notebook.
    except Exception as e:
        # Return a formatted error string so the failure is visible in downstream reports.
        return f"ERROR: API request failed — {e}"

# Print a visible title before running the contract analysis stage.
print_section("STEP 5 — RUN ANALYSIS ON ALL CONTRACTS")

# Create an empty list that will store the final structured analysis records.
analysis_results = []

# Loop through the selected contracts one by one.
for contract in contracts:
    # Print a visible per-contract progress message.
    print(f"🔍 Analyzing: {contract['display_title']}")

    # Run the model analysis only if the API connection test succeeded earlier.
    if api_working:
        # Generate the analysis text for the current contract.
        analysis_text = analyze_contract(contract["content"])
    else:
        # Create a fallback message if the API is unavailable.
        analysis_text = "ERROR: Analysis skipped because the API connection test failed."

    # Build a structured result object that combines input metadata and output text.
    analysis_results.append({
        "sample_id": contract["sample_id"],
        "title": contract["display_title"],
        "filename": contract["filename"],
        "word_count": contract["word_count"],
        "analysis_text": analysis_text,
        "analysis_timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    })

    # Pause briefly between requests to keep the workflow polite and stable.
    time.sleep(1)

# Print a completion message after all contracts have been processed.
print("✅ Contract analysis stage completed")

====================================================================================================
STEP 5 — RUN ANALYSIS ON ALL CONTRACTS
====================================================================================================
🔍 Analyzing: 2ThemartComInc_19990826_10-12G_EX-10.10_6700288_EX-10.10_Co-Branding Agreement_ Agency Agreement
🔍 Analyzing: ABILITYINC_06_15_2020-EX-4.25-SERVICES AGREEMENT
🔍 Analyzing: ACCELERATEDTECHNOLOGIESHOLDINGCORP_04_24_2003-EX-10.13-JOINT VENTURE AGREEMENT
✅ Contract analysis stage completed

## 6. Build the Final Report and Summary Tables

This section converts the raw model outputs into a clean, presentation-friendly report.

### What this section does
This step:
- prints each full contract analysis,
- builds structured summary tables,
- displays the final outputs in a classroom-friendly format.

### Why this step matters
A good NLP demo should not end with raw API output alone.  
It should also organize the results so a human decision-maker can review them efficiently.

### Conceptual mini-flow

```text
Model Analysis Results
          ↓
Organize Into Records
          ↓
Print Human-Readable Report
          ↓
Display Summary Tables
```

In [18]:

# Define a helper function that extracts a short risk label from the model output.
def extract_risk_level(analysis_text):
    # Search for a line that begins with the risk-level heading.
    match = re.search(r"Overall risk level\s*:\s*(.+)", analysis_text, flags=re.IGNORECASE)

    # Return the captured risk label if found.
    if match:
        return match.group(1).strip()

    # Return a fallback label when the pattern is not found.
    return "Not clearly identified"

# Define a helper function that prints a readable report for all analyzed contracts.
def print_final_report(results):
    # Print a visible section header.
    print_section("STEP 6 — FINAL NLP CONTRACT ANALYSIS REPORT")

    # Loop through each analysis result one by one.
    for item in results:
        # Print the contract title.
        print(f"📄 {item['title']}")

        # Print the file name.
        print(f"File name: {item['filename']}")

        # Print the word count.
        print(f"Word count: {item['word_count']}")

        # Print the timestamp of analysis generation.
        print(f"Analysis timestamp: {item['analysis_timestamp']}")

        # Print a divider before the model output.
        print("-" * 80)

        # Print the full analysis text.
        print(item['analysis_text'])

        # Print a closing divider for the current contract.
        print("-" * 100)

# Define a helper function that builds the final summary DataFrames.
def build_final_tables(results):
    # Create an empty list for document-level summary rows.
    summary_rows = []

    # Create an empty list for full analysis rows.
    detailed_rows = []

    # Loop through each result item.
    for item in results:
        # Extract a compact risk label from the analysis text.
        risk_level = extract_risk_level(item["analysis_text"])

        # Build one summary row.
        summary_rows.append({
            "title": item["title"],
            "filename": item["filename"],
            "word_count": item["word_count"],
            "risk_level": risk_level,
            "analysis_timestamp": item["analysis_timestamp"]
        })

        # Build one detailed row.
        detailed_rows.append({
            "title": item["title"],
            "analysis_text": item["analysis_text"]
        })

    # Convert the summary rows into a DataFrame.
    summary_df = pd.DataFrame(summary_rows)

    # Convert the detailed rows into a DataFrame.
    detailed_df = pd.DataFrame(detailed_rows)

    # Return both DataFrames.
    return summary_df, detailed_df

# Print the final readable report.
print_final_report(analysis_results)

====================================================================================================
STEP 6 — FINAL NLP CONTRACT ANALYSIS REPORT
====================================================================================================
📄 2ThemartComInc_19990826_10-12G_EX-10.10_6700288_EX-10.10_Co-Branding Agreement_ Agency Agreement
File name: 2ThemartComInc_19990826_10-12G_EX-10.10_6700288_EX-10.10_Co-Branding Agreement_ Agency Agreement.txt
Word count: 4467
Analysis timestamp: 2026-03-26 07:53:36
--------------------------------------------------------------------------------
PARTIES:
- Party A: i-Escrow, Inc. (“i-Escrow”)
- Party B: 2TheMart.com, Inc. (“2TheMart”)

MAIN PURPOSE:
This Co-Branding and Advertising Agreement establishes a strategic partnership whereby 2TheMart promotes i-Escrow’s escrow services to its auction users via co-branded digital channels, and i-Escrow implements and operates those services—including a custom-integrated, co-branded website (www.iescrow.com/2TheMart) and an automated information transfer mechanism—to enable seamless transaction initiation. The agreement governs joint branding, content licensing, advertising compensation, service standards, and mutual indemnities. It is fundamentally a technology-enabled marketing and referral arrangement centered on facilitating secure online auction payments through escrow.

MAIN RIGHTS AND OBLIGATIONS:
- Party A obligations (i-Escrow):
  • Develop, host, and maintain the Co-Branded Site (including domain www.iescrow.com/2TheMart) and implement the Information Transfer Mechanism in coordination with 2TheMart;
  • Operate Escrow Services in compliance with California Escrow Law (Financial Code §17000 et seq.);
  • Provide quarterly reporting on Transaction Inquiries, registrations, completed Transactions, and total dollar value;
  • Pay advertising fees to 2TheMart based on Transaction Inquiries (calculated as 0.025% × prior quarter’s average Transaction value);
  • Maintain audit-ready books for payment calculations and permit annual CPA audits;
  • Use 2TheMart Marks only as authorized, with prior written consent, and remove all 2TheMart Content/Marks upon termination.

- Party B obligations (2TheMart):
  • Promote i-Escrow’s Services to sellers and high bidders via end-of-auction emails, FAQ links, seller listing pages, and item/bidding pages;
  • Collaborate in good faith to define and implement the Information Transfer Mechanism (including engineering resources and timely testing);
  • Provide 2TheMart Content and Marks for use on the Co-Branded Site under licensed terms;
  • Approve (or reasonably withhold approval of) i-Escrow’s banner ads and maintain an updated list of prohibited competitor advertisers;
  • Remove i-Escrow Content/Marks from its platforms upon termination and honor confidentiality obligations.

KEY TERMS:
- Payment or value terms:
  • i-Escrow pays 2TheMart advertising fees calculated as **0.025% of the average Transaction value from the prior quarter**, applied per Transaction Inquiry;
  • Fee formula may be adjusted (“Adjusted Rate”) only by mutual written consent after good-faith negotiation;
  • Quarterly reporting required within 2 weeks of quarter-end;
  • Audit rights granted to 2TheMart (annual, at its expense unless underpayment >10%, triggering i-Escrow reimbursement of audit costs).

- Duration or important dates:
  • Effective Date: June 21, 1999;
  • Launch Date: First public deployment of Co-Branded Site + live Information Transfer Mechanism (post-beta);
  • Term: One (1) year following Launch Date, with automatic one-year renewals unless either party provides ≥30 days’ non-renewal notice;
  • Development deadlines: SOW must be agreed within 2 months of Effective Date; Launch Date must occur within 4 months—or either party may terminate.

- Termination conditions:
  • For material breach (60-day cure period);
  • Failure to agree on SOW within 2 months (Section 2.2);
  • Failure to achieve Launch Date within 4 months (Section 2.3), *if the terminating party can demonstrate it used good-faith efforts*;
  • Change in control (majority equity acquisition), with 30-day notice;
  • Bankruptcy or insolvency events (Section 8.4);
  • Force majeure lasting ≥60 days;
  • Mutual written agreement.

- Liability or indemnity observations:
  • Mutual indemnity for third-party claims arising from each party’s Content (2TheMart for 2TheMart Content; i-Escrow for i-Escrow Content and Services);
  • Broad indemnity also extends to claims where the Indemnified Party is deemed a “principal” of the Indemnifying Party — a potentially expansive liability trigger;
  • Express exclusion of consequential, special, or punitive damages (Section 10), except for breaches of Section 11 (Confidentiality);
  • No warranty beyond “AS IS”; explicit disclaimer of merchantability, fitness for purpose, title, and non-infringement.

- Governing law or jurisdiction, if available:
  • Governed by California law (excluding conflict-of-law principles);
  • Exclusive venue: courts in Orange County, California;
  • Parties submit to personal jurisdiction in California.

RISK LEVEL:
- Overall risk level: **Medium**
- Main risk factors:
  • **Revenue model volatility**: Advertising fee tied to *average Transaction value*, which is subject to fluctuation and requires accurate, auditable calculation—risk of dispute over averaging methodology or data integrity;
  • **Integration dependency & launch risk**: Success hinges on timely, functional development of the Information Transfer Mechanism—a complex technical interface with strict deadlines (2-month SOW window, 4-month Launch deadline) and mutual cooperation requirements;
  • **Asymmetric termination triggers**: While both parties may terminate for missed deadlines, only the party demonstrating “good faith and reasonable efforts” may exercise that right—creating potential for subjective disputes and litigation over effort standards;
  • **Broad indemnity scope**: The “principal”-based indemnity (Section 9) lacks definition and could expose either party to unforeseen vicarious liability beyond direct content or service failures;
  • **Regulatory exposure**: i-Escrow’s obligation to comply with California Escrow Law introduces regulatory compliance risk—and while the Agreement states law prevails over conflicting terms, no mechanism ensures ongoing alignment or regulatory updates are addressed.

EXECUTIVE SUMMARY:
- This is a co-branding and referral agreement enabling 2TheMart to embed i-Escrow’s escrow services into its auction platform via a dedicated co-branded site (www.iescrow.com/2TheMart) and automated data integration—designed to reduce friction for buyers/sellers completing high-value transactions.
- Compensation is performance-based: i-Escrow pays 2TheMart a variable advertising fee per Transaction Inquiry, calculated as 0.025% of the prior quarter’s average Transaction value—creating revenue linkage but also measurement and audit complexity.
- Time-bound development milestones are critical: Failure to finalize the technical integration (SOW) within 2 months or go live (Launch Date) within 4 months permits termination—highlighting execution risk and interdependence.
- Both parties grant limited, non-exclusive licenses to each other’s trademarks and content,
----------------------------------------------------------------------------------------------------
📄 ABILITYINC_06_15_2020-EX-4.25-SERVICES AGREEMENT
File name: ABILITYINC_06_15_2020-EX-4.25-SERVICES AGREEMENT.txt
Word count: 4115
Analysis timestamp: 2026-03-26 07:54:32
--------------------------------------------------------------------------------
PARTIES:
- Party A: [ * * * ] (the “Provider”)
- Party B: TELCOSTAR PTE. LTD. (Singapore) and Ability Computer & Software Industries Ltd (Israel) — jointly and severally referred to as the “Recipient”

MAIN PURPOSE:
This Services Agreement governs the provision of outsourced services by the Provider to the Recipient, effective November 1, 2019. The Provider delivers personnel, infrastructure, and operational support (detailed in Exhibit A) to enable the Recipient’s business operations. The arrangement is structured as an independent contractor engagement—not employment or partnership—with strict controls over service quality, confidentiality, intellectual property, and data handling. It contemplates both baseline services and potential good-faith expansion to additional services upon mutual agreement.

MAIN RIGHTS AND OBLIGATIONS:
- Party A obligations:
  • Provide Services per Exhibit A, maintaining historical standards of care and continuity (including dedicated, pre-approved personnel).
  • Maintain all software/hardware used for Services with same diligence as for its own operations.
  • Assign all IP created in connection with Services to Recipient; execute assignments and assist in securing protections.
  • Bear full responsibility (including financial liability) for subcontractors’ performance and compliance.
  • Maintain accurate records, deliver monthly invoices with supporting documentation, and comply with post-termination obligations (e.g., return/destroy Confidential Information, refund unearned fees).
  • Indemnify Recipient against third-party claims arising from Provider’s negligence, willful misconduct, or breach.

- Party B obligations:
  • Pay Provider’s actual costs plus 10% service fee, plus reimbursement of documented Out-of-Pocket Costs (e.g., licenses, subcontractor payments).
  • Pay invoices within 15 days of receipt; resolve disputes in writing prior to due date.
  • Accept assignment of all IP and confidential deliverables generated under the Agreement.
  • Maintain confidentiality of Provider’s information and restrict use of Confidential Information to Permitted Purpose only.
  • Comply with termination notice requirements and cooperate on transition (e.g., facilitate access for handover).

KEY TERMS:
- Payment or value terms:
  • Compensation = Provider’s actual cost + 10% service fee + reimbursable, documented Out-of-Pocket Costs.
  • No right of setoff permitted.
  • Provider grants Recipient free use of [ * * * ] through December 31, 2021.

- Duration or important dates:
  • Effective Date: November 1, 2019.
  • Scheduled Termination Date: December 31, 2020 (unless earlier terminated).
  • Free-use license for [ * * * ] expires December 31, 2021.

- Termination conditions:
  • Either Party may terminate without cause upon 90 days’ written notice.
  • For material breach: 30-day cure period after written notice (non-payment not subject to good-faith dispute is deemed uncured breach).
  • Automatic termination upon insolvency events (e.g., bankruptcy filing, receivership).
  • Force Majeure permits suspension and, if >3 months, termination of Affected Services only.

- Liability or indemnity observations:
  • Provider provides broad indemnity covering losses from its negligence, willful misconduct, or breach — including defense costs and third-party claims.
  • Provider retains full liability for subcontractors’ acts/omissions.
  • No limitation of liability clause is present; indemnity scope is uncapped and expressly includes attorneys’ fees and enforcement costs.
  • Specific performance and injunctive relief are expressly available for breaches (e.g., IP misuse, confidentiality violations).

- Governing law or jurisdiction, if available:
  • Governing law: Substantive domestic law of the State of Israel (excluding conflict-of-law rules).
  • Jurisdiction: Exclusive venue in Tel Aviv, Israel — *except* Recipient may seek injunctive relief in Provider’s country of breach.

RISK LEVEL:
- Overall risk level: **Medium–High**
- Main risk factors:
  • **Unbounded indemnity exposure**: Provider assumes uncapped liability for negligence/misconduct/breach — no monetary caps, exclusions for consequential damages, or carve-outs for indirect losses.
  • **IP ownership is absolute and automatic**: All work product, inventions, and code are “works made for hire” or irrevocably assigned — creates high dependency on Provider’s compliance and recordkeeping.
  • **Personnel rigidity**: Provider Representatives cannot be changed without Recipient’s consent — poses operational risk if key staff depart or become unavailable.
  • **No service-level agreements (SLAs) or KPIs**: Performance standard is vague (“historically consistent”), with no measurable benchmarks, penalties, or credits for failure.
  • **Jurisdictional complexity**: Dual-recipient structure (Singapore + Israel entities) combined with Israeli governing law and Tel Aviv forum creates cross-border enforcement and coordination challenges.
  • **Confidentiality asymmetry**: While mutual, the definition heavily favors Recipient’s commercial/technical data; Provider’s confidential information receives comparatively less protection specificity.

EXECUTIVE SUMMARY:
- This is a high-control, IP-forward services outsourcing agreement where the Provider acts as a dedicated, non-exclusive resource arm for the Recipient — with full IP transfer, strict personnel controls, and robust confidentiality safeguards.
- Compensation is cost-plus-10% with full expense pass-through, offering transparency but limited predictability for Recipient budgeting — especially given absence of caps on Out-of-Pocket Costs.
- Termination is flexible (90-day no-cause exit), but post-termination obligations are extensive and enforceable via injunction — including mandatory data erasure, physical asset return, and written certification of compliance.
- The Provider bears significant legal and financial risk: uncapped indemnity, sole liability for subcontractors, and strict adherence to historical service standards — yet lacks corresponding service-level guarantees or remedies for Recipient non-payment delays beyond interest-free late payment terms.
- Governing law (Israel) and exclusive Tel Aviv jurisdiction introduce complexity for the Singapore-based Recipient entity and the unnamed Provider — requiring careful attention to cross-border enforceability, tax, and data residency implications.
- Critical gaps include missing SLAs, no defined dispute escalation process beyond “good faith,” and silence on data privacy compliance (e.g., GDPR, PDPA), which is material given international parties and likely processing of personal data.
----------------------------------------------------------------------------------------------------
📄 ACCELERATEDTECHNOLOGIESHOLDINGCORP_04_24_2003-EX-10.13-JOINT VENTURE AGREEMENT
File name: ACCELERATEDTECHNOLOGIESHOLDINGCORP_04_24_2003-EX-10.13-JOINT VENTURE AGREEMENT.txt
Word count: 1911
Analysis timestamp: 2026-03-26 07:55:28
--------------------------------------------------------------------------------
PARTIES:
- Party A: Collectible Concepts Group, Inc. ("CCGI")
- Party B: Pivotal Self Service Tech, Inc. ("PVSS")

MAIN PURPOSE:
This Joint Venture Agreement establishes a non-partnership, tax-elective joint venture named “MightyCell Batteries” for the purpose of marketing and distributing licensed batteries and related products—distinct from PVSS’s standard branded offerings (“PVSS Products”). The venture is structured to leverage CCGI’s branding, licensing, and go-to-market capabilities alongside PVSS’s product supply, sourcing, and fulfillment expertise. Critically, the Parties explicitly disclaim partnership status for legal and U.S. federal income tax purposes and elect out of Subchapter K under IRC §761(a). The arrangement is time-bound, operationally lean (no mandatory capital contributions), and governed by Pennsylvania law.

MAIN RIGHTS AND OBLIGATIONS:
- Party A obligations:
  • Obtain licenses for branded/logos/images used on Products (Exhibit A.1);
  • Prepare artwork for licensed/branded Products and packaging (Exhibit A.2);
  • Collaborate with PVSS to appoint sales agents/distributors for retail channels (Exhibit A.3);
  • Develop marketing materials for sales support (Exhibit A.4);
  • Conduct promotional and sales support activities (Exhibit A.5);
  • Provide primary fulfillment services via affiliates (Exhibit A.6).

- Party B obligations:
  • Supply Products per CCGI-specified specifications, quantities, and timelines (Exhibit A.1);
  • Provide additional salable Products as jointly determined (Exhibit A.2);
  • Negotiate favorable supplier pricing and terms to ensure JV viability and continuity (Exhibit A.3);
  • Serve as backup fulfillment/distribution provider (Exhibit A.4).

KEY TERMS:
- Payment or value terms:
  • Income, losses, credits, and deductions shared equally (50/50) per Section 6;
  • No compensation for services rendered—but full reimbursement of *direct*, out-of-pocket expenses (Section 5);
  • Distributions permitted only from gross income *not needed* for expected costs/expenses—and only if post-distribution assets exceed liabilities (Section 9);
  • All unallocated expenses apportioned per GAAP (Section 6).

- Duration or important dates:
  • Term: March 1, 2003 – February 28, 2004 (one year);
  • Automatic termination unless extended by written agreement ≥30 days prior to expiration (Section 8).

- Termination conditions:
  • Expiration of term without extension (Section 8);
  • Mutual agreement to terminate;
  • Upon termination: debts paid or provided for; remaining funds distributed 50/50; non-cash assets distributed as undivided interests ratably—or monetized and balanced in cash/property to achieve 50/50 equity (Section 11).

- Liability or indemnity observations:
  • No explicit indemnity clause; however, each Party is liable for its own acts/omissions;
  • Joint Venturers jointly authorize key actions (e.g., incurring debt, disposing assets, major purchases) — requiring *unanimous written consent* (Section 5);
  • Neither Party is liable for the other’s separate business activities (Sections 5, 10);
  • Reimbursement limited to *direct* expenses — no coverage for overhead, indirect costs, or opportunity costs.

- Governing law or jurisdiction, if available:
  • Governed by and construed under the laws of the Commonwealth of Pennsylvania (Section 14);
  • Explicit carve-out for instances where another jurisdiction’s law “necessarily controls” (e.g., intellectual property rights, federal tax elections).

RISK LEVEL:
- Overall risk level: Medium
- Main risk factors:
  • **Tax election fragility**: IRC §761(a) election requires strict adherence (e.g., timely filing of Form 8832 or equivalent); failure could trigger unintended partnership tax treatment, exposing Parties to joint liability for JV-level taxes, filings, and penalties;
  • **Operational ambiguity**: No defined governance body (e.g., JV committee), decision-making thresholds beyond unanimity for major acts, or dispute resolution mechanism — increasing deadlock and execution risk;
  • **Fulfillment dependency & overlap**: CCGI provides primary fulfillment; PVSS provides backup — but Exhibit A lacks SLAs, performance standards, or transition protocols, creating service continuity and accountability gaps;
  • **Short, inflexible term**: One-year fixed term with no automatic renewal or exit ramp — limits strategic runway and increases pressure to achieve commercial traction rapidly;
  • **No IP ownership clarity**: While CCGI obtains licenses and creates artwork, the Agreement is silent on ownership, license scope (field, territory, duration), or JV’s rights to use such IP post-termination — posing significant post-venture brand and asset risk.

EXECUTIVE SUMMARY:
- Establishes a time-limited (March 2003–February 2004), 50/50 revenue-and-loss-sharing joint venture — MightyCell Batteries — focused on marketing licensed battery products distinct from PVSS’s core offerings.
- Structured as a non-partnership for legal and U.S. tax purposes, with an explicit IRC §761(a) election to exclude the venture from Subchapter K — requiring careful IRS compliance to avoid adverse tax consequences.

In [19]:
# Build the final DataFrames used for notebook display.
summary_df, detailed_df = build_final_tables(analysis_results)

In [20]:
# Print a visible title before displaying the compact summary table.
print_section("DOCUMENT-LEVEL SUMMARY TABLE")

# Display the compact summary table.
display(summary_df)

====================================================================================================
DOCUMENT-LEVEL SUMMARY TABLE
====================================================================================================

,title,filename,word_count,risk_level,analysis_timestamp
0,2ThemartComInc_19990826_10-12G_EX-10.10_670028...,2ThemartComInc_19990826_10-12G_EX-10.10_670028...,4467,**Medium**,2026-03-26 07:53:36
1,ABILITYINC_06_15_2020-EX-4.25-SERVICES AGREEMENT,ABILITYINC_06_15_2020-EX-4.25-SERVICES AGREEME...,4115,**Medium–High**,2026-03-26 07:54:32
2,ACCELERATEDTECHNOLOGIESHOLDINGCORP_04_24_2003-...,ACCELERATEDTECHNOLOGIESHOLDINGCORP_04_24_2003-...,1911,Medium,2026-03-26 07:55:28

In [21]:
# Print a visible title before displaying the full analysis table.
print_section("FULL CONTRACT ANALYSIS TABLE")

# Display the full analysis table.
display(detailed_df)

====================================================================================================
FULL CONTRACT ANALYSIS TABLE
====================================================================================================

,title,analysis_text
0,2ThemartComInc_19990826_10-12G_EX-10.10_670028...,"PARTIES: \n- Party A: i-Escrow, Inc. (“i-Escr..."
1,ABILITYINC_06_15_2020-EX-4.25-SERVICES AGREEMENT,PARTIES: \n- Party A: [ * * * ] (the “Provide...
2,ACCELERATEDTECHNOLOGIESHOLDINGCORP_04_24_2003-...,PARTIES: \n- Party A: Collectible Concepts Gr...